// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shut-api.proto

package com.zhashut.shutapigateway.proto;

public interface RequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Request)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string requestData = 1;</code>
   * @return The requestData.
   */
  String getRequestData();
  /**
   * <code>string requestData = 1;</code>
   * @return The bytes for requestData.
   */
  com.google.protobuf.ByteString
      getRequestDataBytes();
}
