// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: shut-api.proto

package com.zhashut.shutapigateway.proto;

public interface ResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Response)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseData = 1;</code>
   * @return The responseData.
   */
  String getResponseData();
  /**
   * <code>string responseData = 1;</code>
   * @return The bytes for responseData.
   */
  com.google.protobuf.ByteString
      getResponseDataBytes();
}
